### ISSUE TITLE
Comic Sans font not supported

### ISSUE THREAD

**Issue by vingkan** [bbatliner/electron-wrapper#2] opened 2015-12-01 08:24 UTC
hello

I tried to "wrap" (that's the verb, right?) a window from a brilliant hack called funfacts.js but electron-wrapper changed the font from comic sans to times new roman

please fix
# thank

**Comment by bbatliner** [comment] 2015-12-01 08:27
I was unable to replicate the issue and it's not intended behavior. Closing this issue.

#welcome

**Closed as completed by bbatliner** 2015-12-01 08:27 UTC

**Comment by vingkan** [comment] 2015-12-01 08:29
okay thank you for your hard work on this project that has received thousands of downloads
